name: cricketbuzz
description: "CricketBuzz - Live Cricket Scores & Stats"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_remote_config: ^5.4.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_storage: ^12.4.4
  firebase_performance: ^0.10.0+15

  # Auth
  google_sign_in: ^6.2.2

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.8

  # Navigation
  go_router: ^15.1.2

  # Dependency Injection
  get_it: ^8.0.3

  # Storage
  shared_preferences: ^2.5.4

  # Network & Data
  http: ^1.4.0
  html: ^0.15.4
  connectivity_plus: ^6.1.4

  # UI
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  flutter_svg: ^2.1.0

  # Ads
  google_mobile_ads: ^7.0.0
  gma_mediation_unity: ^1.6.5
  gma_mediation_meta: ^1.5.1
  gma_mediation_ironsource: 2.2.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.2
  timeago: ^3.7.0

  app_tracking_transparency: ^2.0.6+1
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  confetti: ^0.8.0
  audioplayers: ^6.5.1
  fl_pip: ^3.2.1
  purchases_flutter: ^9.12.2
  flutter_dotenv: ^5.2.1
  purchases_ui_flutter: ^9.12.2
  upgrader: ^12.5.0
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

