// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPbh9RQf_peg77rlUoOmCtO-3fzSy4hQ',
    appId: '1:140223746923:android:84f61239d48fd51e65b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2d2wJLogsuiAgrrk51wN-_AuyTyWfiGI',
    appId: '1:140223746923:ios:cfb2ae8795bc178465b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.firebasestorage.app',
    androidClientId:
        '140223746923-15om8fotr173csrghjk7rai3dajesi2s.apps.googleusercontent.com',
    iosClientId:
        '140223746923-ik5th9ami9tulnqofu5t8l8d4e4fif0a.apps.googleusercontent.com',
    iosBundleId: 'com.qdevix.cricket_live_score_2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2d2wJLogsuiAgrrk51wN-_AuyTyWfiGI',
    appId: '1:140223746923:ios:cfb2ae8795bc178465b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.firebasestorage.app',
    androidClientId:
        '140223746923-15om8fotr173csrghjk7rai3dajesi2s.apps.googleusercontent.com',
    iosClientId:
        '140223746923-ik5th9ami9tulnqofu5t8l8d4e4fif0a.apps.googleusercontent.com',
    iosBundleId: 'com.qdevix.cricket_live_score_2026',
  );
}
